# Generated by Django 5.1.6 on 2025-11-19 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('total_calculations', models.IntegerField(default=0)),
                ('potencia_calculations', models.IntegerField(default=0)),
                ('espiras_calculations', models.IntegerField(default=0)),
                ('diagrama_calculations', models.IntegerField(default=0)),
                ('geographic_data', models.JSONField(default=dict)),
                ('top_states', models.JSONField(default=list)),
                ('top_cities', models.JSONField(default=list)),
                ('mobile_visits', models.IntegerField(default=0)),
                ('desktop_visits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumo Diário de Estatísticas',
                'verbose_name_plural': 'Resumos Diários de Estatísticas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('state_code', models.CharField(max_length=2, unique=True)),
                ('region', models.CharField(choices=[('norte', 'Norte'), ('nordeste', 'Nordeste'), ('centro-oeste', 'Centro-Oeste'), ('sudeste', 'Sudeste'), ('sul', 'Sul')], max_length=20)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'verbose_name': 'Região Geográfica',
                'verbose_name_plural': 'Regiões Geográficas',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('path', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, default='Brasil', max_length=100)),
                ('country_code', models.CharField(blank=True, default='BR', max_length=10)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('access_type', models.CharField(choices=[('page_view', 'Visualização de Página'), ('calculation', 'Cálculo Realizado'), ('download', 'Download'), ('form_submit', 'Formulário Enviado')], default='page_view', max_length=50)),
                ('calculation_type', models.CharField(blank=True, choices=[('potencia', 'Cálculo de Potência'), ('espiras', 'Cálculo de Espiras'), ('diagrama', 'Geração de Diagrama')], max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'state', 'city'], name='analytics_a_timesta_b3dc5e_idx'), models.Index(fields=['date', 'access_type'], name='analytics_a_date_24dce2_idx')],
            },
        ),
    ]
