# Generated by Django 5.2.8 on 2025-11-15 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S', models.IntegerField(help_text='Número de ranhuras do estator (slots)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Ranhuras')),
                ('P', models.IntegerField(help_text='Número de polos do motor', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Número de Polos')),
                ('g_type', models.CharField(choices=[('g=P', 'g=P'), ('g=P/2', 'g=P/2')], help_text='Configuração do número de grupos', max_length=10, verbose_name='Tipo de g')),
                ('Camada', models.CharField(choices=[('única', 'Camada Única'), ('dupla', 'Camada Dupla')], help_text='Configuração de camada única ou dupla', max_length=10, verbose_name='Tipo de Camada')),
                ('q', models.DecimalField(decimal_places=2, help_text='Número de ranhuras por polo por fase', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor de q')),
                ('tipo_q', models.CharField(choices=[('inteiro', 'Inteiro'), ('fracionário', 'Fracionário')], help_text='Indica se q é inteiro ou fracionário', max_length=15, verbose_name='Tipo de q')),
                ('n_bob_info', models.CharField(help_text='Número de bobinas ou distribuição por grupo', max_length=50, verbose_name='Informação de Bobinas')),
                ('y', models.IntegerField(help_text='Passo de bobinagem', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Passo Polar')),
                ('zeta', models.DecimalField(decimal_places=4, help_text='Fator de distribuição de enrolamento', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fator Zeta')),
                ('Classificacao_zeta', models.CharField(choices=[('excelente', 'Excelente'), ('bom', 'Bom'), ('aceitável', 'Aceitável'), ('evitar', 'Evitar')], help_text='Classificação da qualidade da configuração', max_length=15, verbose_name='Classificação')),
                ('Observacao_passo', models.CharField(blank=True, default='', help_text='Observações sobre a recomendação do passo', max_length=50, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Motor',
                'verbose_name_plural': 'Configurações de Motores',
                'ordering': ['S', 'P', 'g_type', 'Camada', 'y'],
                'indexes': [models.Index(fields=['S'], name='idx_ranhuras'), models.Index(fields=['S', 'P'], name='idx_ranhuras_polos'), models.Index(fields=['S', 'P', 'Camada'], name='idx_ranhuras_polos_camada'), models.Index(fields=['S', 'P', 'g_type'], name='idx_ranhuras_polos_gtype'), models.Index(fields=['Classificacao_zeta'], name='idx_classificacao')],
                'unique_together': {('S', 'P', 'g_type', 'Camada', 'y')},
            },
        ),
    ]
